on:
  issues:
    types: [workflow_dispatch]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const issues = github.rest.issues.get({
              state: "open",
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            console.log(issues.length)
