on:
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT || github.token }}
          script: |
            const issues = github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            console.log(issues.length)
