on:
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: get-count
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const issues = await github.rest.issues.listForRepo({
              state: "closed",
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            return issues.data.length
      - name: Check result
        if: steps.get-count.outputs.result > 10
        run:  echo "${{steps.get-count.outputs.result}}"
          
