name: Send email when issue created
on:
  issues:
    types: [opened]

jobs:
  issue-opened:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: get-count
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const issues = await github.rest.issues.listForRepo({
              creator: "maxneuvians",
              state: "open",
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
      - name: Sends email to max
        uses: cds-snc/gc-notification-github-action@main
        if: steps.get-count.outputs.result > 10
        env: 
          BODY: '{"subject": "More than 10 sites are down", "body": "[View details](${{ github.event.issue.html_url }})"}'
        with:
          api-key: ${{ secrets.NOTIFY_API_KEY }}
          personalisation: ${{ env.BODY }}
          recipient: max@neuvians.net
          template-id: ${{ secrets.EMAIL_TEMPLATE_ID }}
