name: Send email when issue created
on:
  issues:
    types: [opened]

jobs:
  issue-opened:
    runs-on: ubuntu-latest
    steps:
      - name: Sends email to max
        uses: cds-snc/gc-notification-github-action@main
        env: 
          BODY: '{"subject": "${{ github.event.issue.title }}", "body": "[View details](${{ github.event.issue.html_url }})"}'
        with:
          api-key: ${{ secrets.NOTIFY_API_KEY }}
          personalisation: ${{ env.BODY }}
          recipient: max@neuvians.net
          template-id: ${{ secrets.EMAIL_TEMPLATE_ID }}
