name: New Static Site CI
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
jobs:
  release:
    name: Build and deploy site
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || github.token }}
      - uses: peaceiris/actions-gh-pages@v3.7.3
        name: GitHub Pages Deploy
        with:
          github_token: ${{ secrets.GH_PAT || github.token }}
          publish_dir: "static/"
          force_orphan: "false"
          user_name: "Upptime Bot"
          user_email: "73812536+upptime-bot@users.noreply.github.com"
